server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            - After=2022-03-26T14:58:10.424+08:00[Asia/Shanghai]
            #- Cookie=username,zyx
            #- Header=X-Request-Id, \d+
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    hostname: cloud-gateway-service